using System.Text.RegularExpressions;

namespace Platform.Infrastructure.DataDesigner;

/// <summary>
/// The single choke point every table/column/schema name generated by the Data Designer passes
/// through before it reaches a SQL string. Identifiers are never string-concatenated as-is: they
/// are validated against a strict allow-list charset first, then always double-quoted, so a name
/// like `x"; DROP TABLE` is rejected outright rather than merely escaped.
/// </summary>
public static class SqlIdentifiers
{
    private static readonly Regex ValidIdentifier = new("^[a-zA-Z_][a-zA-Z0-9_]{0,62}$", RegexOptions.Compiled);

    public static void Validate(string identifier, string fieldName)
    {
        if (string.IsNullOrWhiteSpace(identifier) || !ValidIdentifier.IsMatch(identifier))
        {
            throw new ArgumentException(
                $"{fieldName} '{identifier}' is invalid. Use 1-63 characters, starting with a letter " +
                "or underscore, containing only letters, digits, and underscores.");
        }
    }

    /// <summary>Validates then double-quotes an identifier for safe interpolation into DDL text.</summary>
    public static string Quote(string identifier, string fieldName)
    {
        Validate(identifier, fieldName);
        return $"\"{identifier}\"";
    }

    public static string QualifiedTable(string schemaName, string tableName)
    {
        return $"{Quote(schemaName, "Schema name")}.{Quote(tableName, "Table name")}";
    }

    /// <summary>Deterministic, always-valid schema name for an application's generated tables -
    /// never user-supplied, so no validation is needed at the call site.</summary>
    public static string SchemaNameFor(Guid applicationId) => $"app_{applicationId:N}";
}
