namespace NovaERP.Application.DTOs;

public class ProductDto
{
    public int     Id            { get; set; }
    public string  Sku           { get; set; } = string.Empty;
    public string  Name          { get; set; } = string.Empty;
    public string? Description   { get; set; }
    public string  UnitOfMeasure { get; set; } = string.Empty;
    public decimal UnitCost      { get; set; }
    public decimal? WeightKg     { get; set; }
    public bool    IsActive      { get; set; }

    /// <summary>Sum of this product's StockMovement.Quantity — computed on read, not stored.</summary>
    public decimal OnHandQuantity { get; set; }
}

public class CreateProductDto
{
    public string  Sku           { get; set; } = string.Empty;
    public string  Name          { get; set; } = string.Empty;
    public string? Description   { get; set; }
    public string  UnitOfMeasure { get; set; } = "EA";
    public decimal UnitCost      { get; set; }
    public decimal? WeightKg     { get; set; }
    public bool    IsActive      { get; set; } = true;
}

/// <summary>Sku is immutable after creation — same "identifying field frozen on edit"
/// convention as TaxCode's Code / ExchangeRate's currency pair.</summary>
public class UpdateProductDto
{
    public string  Name          { get; set; } = string.Empty;
    public string? Description   { get; set; }
    public string  UnitOfMeasure { get; set; } = "EA";
    public decimal UnitCost      { get; set; }
    public decimal? WeightKg     { get; set; }
    public bool    IsActive      { get; set; } = true;
}

public class StockMovementDto
{
    public int       Id            { get; set; }
    public int        ProductId     { get; set; }
    public string     ProductName   { get; set; } = string.Empty;
    public string     ProductSku    { get; set; } = string.Empty;
    public int?        WarehouseId   { get; set; }
    public string?     WarehouseName { get; set; }
    public string     MovementType  { get; set; } = string.Empty;
    public decimal    Quantity      { get; set; }
    public string?     EntityType    { get; set; }
    public int?        EntityId      { get; set; }
    public DateTime    MovementDate  { get; set; }
    public string?     Notes         { get; set; }
}

/// <summary>The manual-adjustment creation path — Receipt/Issue movements generated by
/// PurchaseOrder.Receive/SalesOrder.Confirm are created internally by those services, not
/// through this DTO. WarehouseId is optional — same "defer the FK" reasoning as ProductId on
/// SalesOrderLine/PurchaseOrderLine.</summary>
public class CreateStockMovementDto
{
    public int      ProductId    { get; set; }
    public int?     WarehouseId  { get; set; }
    public string   MovementType { get; set; } = "Adjustment";
    public decimal  Quantity     { get; set; }
    public string?  Notes        { get; set; }
}
