namespace NovaERP.Application.DTOs;

public class EmployeeCompensationDto
{
    public int    Id             { get; set; }
    public int    EmployeeId     { get; set; }
    public string EmployeeName   { get; set; } = string.Empty;
    public string EmployeeCode   { get; set; } = string.Empty;

    public decimal BasicSalary     { get; set; }
    public decimal Hra             { get; set; }
    public decimal OtherAllowances { get; set; }
    public decimal Deductions      { get; set; }

    /// <summary>Both computed on read, never stored.</summary>
    public decimal GrossPay { get; set; }
    public decimal NetPay   { get; set; }
}

public class CreateEmployeeCompensationDto
{
    public int EmployeeId { get; set; }

    public decimal BasicSalary     { get; set; }
    public decimal Hra             { get; set; }
    public decimal OtherAllowances { get; set; }
    public decimal Deductions      { get; set; }
}

/// <summary>EmployeeId is immutable after creation — same convention as Product.Sku/Warehouse.Code.</summary>
public class UpdateEmployeeCompensationDto
{
    public decimal BasicSalary     { get; set; }
    public decimal Hra             { get; set; }
    public decimal OtherAllowances { get; set; }
    public decimal Deductions      { get; set; }
}

/// <summary>Read-only — PayRunLines are system-generated by ProcessAsync, never user-entered.</summary>
public class PayRunLineDto
{
    public int    Id             { get; set; }
    public int    EmployeeId     { get; set; }
    public string EmployeeName   { get; set; } = string.Empty;
    public string EmployeeCode   { get; set; } = string.Empty;

    public decimal BasicSalary     { get; set; }
    public decimal Hra             { get; set; }
    public decimal OtherAllowances { get; set; }
    public decimal Deductions      { get; set; }
    public decimal GrossPay        { get; set; }
    public decimal NetPay          { get; set; }
}

public class PayRunDto
{
    public int    Id                              { get; set; }
    public string RunNumber                        { get; set; } = string.Empty;
    public int    PeriodMonth                       { get; set; }
    public int    PeriodYear                        { get; set; }
    public int    ExpenseLedgerAccountId            { get; set; }
    public string ExpenseLedgerAccountName          { get; set; } = string.Empty;
    public int    DeductionsPayableLedgerAccountId  { get; set; }
    public string DeductionsPayableLedgerAccountName { get; set; } = string.Empty;
    public string Status                            { get; set; } = string.Empty;
    public int    OwnerId                           { get; set; }
    public string OwnerName                         { get; set; } = string.Empty;
    public int?   PostedJournalEntryId              { get; set; }

    public List<PayRunLineDto> Lines { get; set; } = new();

    /// <summary>Both computed on read from the lines.</summary>
    public decimal TotalGrossPay { get; set; }
    public decimal TotalDeductions { get; set; }
    public decimal TotalNetPay { get; set; }
}

/// <summary>No Lines here — unlike every prior lines-owning module, PayRunLines are
/// system-generated by ProcessAsync, not built by the user.</summary>
public class CreatePayRunDto
{
    public int PeriodMonth                      { get; set; }
    public int PeriodYear                       { get; set; }
    public int ExpenseLedgerAccountId           { get; set; }
    public int DeductionsPayableLedgerAccountId { get; set; }
    public int OwnerId                          { get; set; }
}

public class UpdatePayRunDto
{
    public int PeriodMonth                      { get; set; }
    public int PeriodYear                       { get; set; }
    public int ExpenseLedgerAccountId           { get; set; }
    public int DeductionsPayableLedgerAccountId { get; set; }
    public int OwnerId                          { get; set; }
}

public class PayPayRunDto
{
    public int PaymentLedgerAccountId { get; set; }
}
