namespace NovaERP.Domain.Entities;

/// <summary>An org-scoped payroll cycle for a period. Processing it snapshots every Active
/// employee's current EmployeeCompensation into PayRunLines (no GL effect yet); paying it
/// posts one balanced JournalEntry (Debit ExpenseLedgerAccountId, Credit
/// DeductionsPayableLedgerAccountId, Credit whichever cash/bank account is chosen at pay
/// time). Lines are owned but system-generated by ProcessAsync, never user-entered.</summary>
public class PayRun : BaseEntity
{
    public int    OrganizationId                 { get; set; }
    public string RunNumber                       { get; set; } = string.Empty;
    public int    PeriodMonth                     { get; set; }
    public int    PeriodYear                      { get; set; }
    public int    ExpenseLedgerAccountId          { get; set; }
    public int    DeductionsPayableLedgerAccountId { get; set; }
    public string Status                          { get; set; } = "Draft"; // Draft | Processed | Paid | Cancelled
    public int    OwnerId                         { get; set; }

    /// <summary>Set by PayAsync — traceability back to the GL entry this run produced. Null
    /// until Pay runs.</summary>
    public int? PostedJournalEntryId { get; set; }

    public Organization Organization { get; set; } = null!;
    public LedgerAccount ExpenseLedgerAccount { get; set; } = null!;
    public LedgerAccount DeductionsPayableLedgerAccount { get; set; } = null!;
    public User Owner { get; set; } = null!;
    public JournalEntry? PostedJournalEntry { get; set; }
    public ICollection<PayRunLine> Lines { get; set; } = new List<PayRunLine>();
}
